[package]
name = "we-have-the-technology"
version = "0.1.0"
edition = "2024"

[dependencies]
fs-err = "3.2.2"
prev-iter = "0.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
threadpool = "1.8.1"
